### ISSUE TITLE
ImportError in Python3

### ISSUE THREAD

**Issue by nostrademons** [geeknam/python-gcm#65]
Did #57 make it onto PyPI?  I'm getting:

  >>>Python 3.4.0 (default, Apr 11 2014, 13:05:11) [GCC 4.8.2] on linux
  import gcm
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/usr/local/lib/python3.4/dist-packages/gcm/__init__.py", line 4, in <module>
      GCM = gcm.GCM
    AttributeError: 'module' object has no attribute 'GCM'

when I do 'import gcm' from the Python3.4 console on a fresh installation, Ubuntu Trusty on AWS.  dist-packages shows python-gcm version 0.2.  This was the same error I got locally before #57 was merged.

**Comment by nostrademons** [comment]
After further debugging, it looks like #57 was not merged, and instead we got #60.  There are still some Python3 issues with that - it needs the import fix in 9d9dcc5 and possibly the encoding fixes in ac3b7e0.  The Travis changes would be nice too, to prevent other regressions.

**Comment by etkaDT** [comment]
Hi,
It seems that doing `from . import gcm` instead of `import gcm` in  `__init__.py`  works in both python2 and python3.

**Comment by tadas-subonis** [comment]
Was this fixed?

**Comment by anthonysutardja** [comment]
I've fixed this import issue in this PR:

https://github.com/geeknam/python-gcm/pull/75

**Comment by stleon** [comment]
The same problem in Python 3.5

**Comment by mnemonicflow** [comment]
I can confirm that this issue has been fixed in #75 and should be closed.
Tested that it works with Python 3.4.3 and Python 3.5.0

**Comment by wichert** [comment]
It would be nice to have this in a release on PyPI before this ticket is closed.

**Comment by geeknam** [comment]
Alex, not sure if you've already done this, but we should include 3.5 in the test matrix.

**Comment by mnemonicflow** [comment]
@geeknam I've added Python 3.5 builds to Travis CI: https://travis-ci.org/geeknam/python-gcm/jobs/83496280

As a side note, for a discussion as to why the `import gcm` doesn't work see: http://programmers.stackexchange.com/questions/159503/whats-wrong-with-relative-imports-in-python

> In Python 3 *implicit* relative imports are no longer supported, with absolute imports being the default and explicit relative imports supported with the dot syntax

**Comment by mandarvaze** [comment]
I agree with @wichert 
When will the version with the fix be available on PyPI ?

**Comment by geeknam** [comment]
0.3 version is now live: https://pypi.python.org/pypi/python-gcm

**Comment by mandarvaze** [comment]
Thanks.
